Testing Enumerable Module
Phylis05/Enumerables pull request #5
Opened 2020-05-06 07:55 UTC by Phylis05

# In this PR we:

- Add specs for all methods created in the Enumerable module.
- Wrapped specs for each method in describe block.
- Used let to define a variable for the test cases.
- Used one it block for each expected behavior.

2020-05-06 18:21 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x]  Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-05-06 18:21 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
Write a test for when a class is passed as an argument

2020-05-06 18:21 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
Write a test for when a class is passed as an argument

2020-05-06 18:21 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
Write a test for when a class is passed as an argument

2020-05-07 13:49 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2020-05-07 14:33 UTC, merged